const albumPanini = {
    "00": { nom: "Panini Logo We Are Panini", equipe: "FIFA", groupe: null, page: 0 },
    "FWC1": { nom: "Official Emblem FIFA World Cup 2026", equipe: "FIFA", groupe: null, page: 1 },
    "FWC2": { nom: "Official Emblem FIFA World Cup 2026", equipe: "FIFA", groupe: null, page: 1 },
    "FWC3": { nom: "Official Mascots FIFA World Cup 2026", equipe: "FIFA", groupe: null, page: 1 },
    "FWC4": { nom: "Official Slogan FIFA World Cup 2026", equipe: "FIFA", groupe: null, page: 1 },
    "FWC5": { nom: "Official Ball FIFA World Cup 2026", equipe: "FIFA", groupe: null, page: 2 },
    "FWC6": { nom: "Canada Host Countries and Cities", equipe: "FIFA", groupe: null, page: 2 },
    "FWC7": { nom: "Mexico Host Countries and Cities", equipe: "FIFA", groupe: null, page: 3 },
    "FWC8": { nom: "USA Host Countries and Cities", equipe: "FIFA", groupe: null, page: 3 },
    "MEX1": { nom: "Emblem", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX2": { nom: "Luis Malagón", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX3": { nom: "Johan Vasquez", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX4": { nom: "Jorge Sánchez", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX5": { nom: "Cesar Montes", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX6": { nom: "Jesus Gallardo", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX7": { nom: "Israel Reyes", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX8": { nom: "Diego Lainez", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX9": { nom: "Carlos Rodriguez", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX10": { nom: "Edson Alvarez", equipe: "Mexico", groupe: "A", page: 8 },
    "MEX11": { nom: "Orbelin Pineda", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX12": { nom: "Marcel Ruiz", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX13": { nom: "Team Photo", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX14": { nom: "Érick Sánchez", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX15": { nom: "Hirving Lozano", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX16": { nom: "Santiago Giménez", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX17": { nom: "Raúl Jiménez", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX18": { nom: "Alexis Vega", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX19": { nom: "Roberto Alvarado", equipe: "Mexico", groupe: "A", page: 9 },
    "MEX20": { nom: "Cesar Huerta", equipe: "Mexico", groupe: "A", page: 9 },
    "RSA1": { nom: "Emblem", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA2": { nom: "Ronwen Williams", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA3": { nom: "Sipho Chaine", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA4": { nom: "Aubrey Modiba", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA5": { nom: "Samukele Kabini", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA6": { nom: "Mbekezeli Mbokazi", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA7": { nom: "Khulumani Ndamane", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA8": { nom: "Siyabonga Ngezana", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA9": { nom: "Khuliso Mudau", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA10": { nom: "Nkosinathi Sibisi", equipe: "South Africa", groupe: "A", page: 10 },
    "RSA11": { nom: "Teboho Mokoena", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA12": { nom: "Thalente Mbatha", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA13": { nom: "Team Photo", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA14": { nom: "Bathasi Aubaas", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA15": { nom: "Yaya Sithole", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA16": { nom: "Sipho Mbule", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA17": { nom: "Lyle Foster", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA18": { nom: "Iqraam Rayners", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA19": { nom: "Mohau Nkota", equipe: "South Africa", groupe: "A", page: 11 },
    "RSA20": { nom: "Oswin Appollis", equipe: "South Africa", groupe: "A", page: 11 },
    "KOR1": { nom: "Emblem", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR2": { nom: "Hyeon-woo Jo", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR3": { nom: "Seung-Gyu Kim", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR4": { nom: "Min-jae Kim", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR5": { nom: "Yu-min Cho", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR6": { nom: "Young-woo Seol", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR7": { nom: "Han-beom Lee", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR8": { nom: "Tae-seok Lee", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR9": { nom: "Myung-jae Lee", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR10": { nom: "Jae-sung Lee", equipe: "South Korea", groupe: "A", page: 12 },
    "KOR11": { nom: "In-beom Hwang", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR12": { nom: "Kang-in Lee", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR13": { nom: "Team Photo", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR14": { nom: "Seung-ho Paik", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR15": { nom: "Jens Castrop", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR16": { nom: "Dongg-yeong Lee", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR17": { nom: "Gue-sung Cho", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR18": { nom: "Heung-min Son", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR19": { nom: "Hee-chan Hwang", equipe: "South Korea", groupe: "A", page: 13 },
    "KOR20": { nom: "Hyeon-Gyu Oh", equipe: "South Korea", groupe: "A", page: 13 },
    "CZE1": { nom: "Emblem", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE2": { nom: "Matej Kovar", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE3": { nom: "Jindrich Stanek", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE4": { nom: "Ladislav Krejci", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE5": { nom: "Vladimir Coufal", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE6": { nom: "Jaroslav Zeleny", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE7": { nom: "Tomas Holes", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE8": { nom: "David Zima", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE9": { nom: "Michal Sadilek", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE10": { nom: "Lukas Provod", equipe: "Czechia", groupe: "A", page: 14 },
    "CZE11": { nom: "Lukas Cerv", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE12": { nom: "Tomas Soucek", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE13": { nom: "Team Photo", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE14": { nom: "Pavel Sulc", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE15": { nom: "Matej Vydra", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE16": { nom: "Vasil Kusej", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE17": { nom: "Tomas Chory", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE18": { nom: "Vaclav Cerny", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE19": { nom: "Adam Hlozek", equipe: "Czechia", groupe: "A", page: 15 },
    "CZE20": { nom: "Patrik Schick", equipe: "Czechia", groupe: "A", page: 15 },
    "CAN1": { nom: "Emblem", equipe: "Canada", groupe: "B", page: 16 },
    "CAN2": { nom: "Dayne St.Clair", equipe: "Canada", groupe: "B", page: 16 },
    "CAN3": { nom: "Alphonso Davies", equipe: "Canada", groupe: "B", page: 16 },
    "CAN4": { nom: "Alistair Johnston", equipe: "Canada", groupe: "B", page: 16 },
    "CAN5": { nom: "Samuel Adekugbe", equipe: "Canada", groupe: "B", page: 16 },
    "CAN6": { nom: "Riche Larvea", equipe: "Canada", groupe: "B", page: 16 },
    "CAN7": { nom: "Derek Cornelius", equipe: "Canada", groupe: "B", page: 16 },
    "CAN8": { nom: "Moïse Bombito", equipe: "Canada", groupe: "B", page: 16 },
    "CAN9": { nom: "Kamal Miller", equipe: "Canada", groupe: "B", page: 16 },
    "CAN10": { nom: "Stephen Eustáquio", equipe: "Canada", groupe: "B", page: 16 },
    "CAN11": { nom: "Ismaël Koné", equipe: "Canada", groupe: "B", page: 17 },
    "CAN12": { nom: "Jonathan Osorio", equipe: "Canada", groupe: "B", page: 17 },
    "CAN13": { nom: "Team Photo", equipe: "Canada", groupe: "B", page: 17 },
    "CAN14": { nom: "Jacob Shaffelburg", equipe: "Canada", groupe: "B", page: 17 },
    "CAN15": { nom: "Mathieu Choinière", equipe: "Canada", groupe: "B", page: 17 },
    "CAN16": { nom: "Niko Sigur", equipe: "Canada", groupe: "B", page: 17 },
    "CAN17": { nom: "Tajon Buchanan", equipe: "Canada", groupe: "B", page: 17 },
    "CAN18": { nom: "Liam Millar", equipe: "Canada", groupe: "B", page: 17 },
    "CAN19": { nom: "Cyle Larin", equipe: "Canada", groupe: "B", page: 17 },
    "CAN20": { nom: "Jonathan David", equipe: "Canada", groupe: "B", page: 17 },
    "BIH1": { nom: "Emblem", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH2": { nom: "Nikola Vasilj", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH3": { nom: "Amer Dedic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH4": { nom: "Sead Kolasinac", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH5": { nom: "Tarik Muharemovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH6": { nom: "Nihad Mujakic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH7": { nom: "Nikola Katic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH8": { nom: "Amir Hadziahmetovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH9": { nom: "Benjamin Tahirovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH10": { nom: "Armin Gigovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 18 },
    "BIH11": { nom: "Ivan Sunjic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH12": { nom: "Ivan Basic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH13": { nom: "Team Photo", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH14": { nom: "Dzenis Burnic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH15": { nom: "Esmir Bajraktarevic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH16": { nom: "Amar Memic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH17": { nom: "Ermedin Demirovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH18": { nom: "Edin Dzeko", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH19": { nom: "Samed Bazdar", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "BIH20": { nom: "Haris Tabakovic", equipe: "Bosnia and Herzegovina", groupe: "B", page: 19 },
    "QAT1": { nom: "Emblem", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT2": { nom: "Meshaal Barsham", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT3": { nom: "Sultan Albrake", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT4": { nom: "Lucas Mendes", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT5": { nom: "Homam Ahmed", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT6": { nom: "Boualem Khoukhi", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT7": { nom: "Pedro Miguel", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT8": { nom: "Tarek Salman", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT9": { nom: "Mohamed Al-Mannai", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT10": { nom: "Karim Boudiaf", equipe: "Qatar", groupe: "B", page: 20 },
    "QAT11": { nom: "Assim Madibo", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT12": { nom: "Ahmed Fatehi", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT13": { nom: "Team Photo", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT14": { nom: "Mohammed Waad", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT15": { nom: "Abdulaziz Hatem", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT16": { nom: "Hassan Al-Haydos", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT17": { nom: "Edmilson Junior", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT18": { nom: "Akram Hassan Afif", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT19": { nom: "Ahmed Al Ganehi", equipe: "Qatar", groupe: "B", page: 21 },
    "QAT20": { nom: "Almoez Ali", equipe: "Qatar", groupe: "B", page: 21 },
    "SUI1": { nom: "Emblem", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI2": { nom: "Gregor Kobel", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI3": { nom: "Yvon Mvogo", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI4": { nom: "Manuel Akanji", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI5": { nom: "Ricardo Rodriguez", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI6": { nom: "Nico Elvedi", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI7": { nom: "Aurèle Amenda", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI8": { nom: "Silvan Widmer", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI9": { nom: "Granit Xhaka", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI10": { nom: "Denis Zakaria", equipe: "Switzerland", groupe: "B", page: 22 },
    "SUI11": { nom: "Remo Freuler", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI12": { nom: "Fabian Rieder", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI13": { nom: "Team Photo", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI14": { nom: "Ardon Jashari", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI15": { nom: "Johan Manzambi", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI16": { nom: "Michel Aebischer", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI17": { nom: "Breel Embolo", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI18": { nom: "Ruben Vargas", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI19": { nom: "Dan Ndoye", equipe: "Switzerland", groupe: "B", page: 23 },
    "SUI20": { nom: "Zeki Amdouni", equipe: "Switzerland", groupe: "B", page: 23 },
    "BRA1": { nom: "Emblem", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA2": { nom: "Alisson", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA3": { nom: "Bento", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA4": { nom: "Marquinhos", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA5": { nom: "Éder Militão", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA6": { nom: "Gabriel Magalhães", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA7": { nom: "Danilo", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA8": { nom: "Wesley", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA9": { nom: "Lucas Paquetá", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA10": { nom: "Casemiro", equipe: "Brazil", groupe: "C", page: 24 },
    "BRA11": { nom: "Bruno Guimarães", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA12": { nom: "Luiz Henrique", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA13": { nom: "Team Photo", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA14": { nom: "Vinicius Júnior", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA15": { nom: "Rodrygo", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA16": { nom: "João Pedro", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA17": { nom: "Matheus Cunha", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA18": { nom: "Gabriel Martinelli", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA19": { nom: "Raphinha", equipe: "Brazil", groupe: "C", page: 25 },
    "BRA20": { nom: "Estévão", equipe: "Brazil", groupe: "C", page: 25 },
    "MAR1": { nom: "Emblem", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR2": { nom: "Yassine Bounou", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR3": { nom: "Munir El Kajoui", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR4": { nom: "Achraf Hakimi", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR5": { nom: "Noussair Mazraoui", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR6": { nom: "Nayef Aguerd", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR7": { nom: "Roman Saiss", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR8": { nom: "Jawad El Yamio", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR9": { nom: "Adam Masina", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR10": { nom: "Sofyan Amrabat", equipe: "Morocco", groupe: "C", page: 26 },
    "MAR11": { nom: "Azzedine Ounahi", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR12": { nom: "Eliesse Ben Seghir", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR13": { nom: "Team Photo", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR14": { nom: "Bilal El Khannouss", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR15": { nom: "Ismael Saibari", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR16": { nom: "Youssef En-Nesyri", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR17": { nom: "Abde Ezzalzouli", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR18": { nom: "Soufiane Rahimi", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR19": { nom: "Brahim Diaz", equipe: "Morocco", groupe: "C", page: 27 },
    "MAR20": { nom: "Ayoub El Kaabi", equipe: "Morocco", groupe: "C", page: 27 },
    "HAI1": { nom: "Emblem", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI2": { nom: "Johny Placide", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI3": { nom: "Carlens Arcus", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI4": { nom: "Martin Expérience", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI5": { nom: "Jean-Kevin Duverne", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI6": { nom: "Ricardo Adé", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI7": { nom: "Duke Lacroix", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI8": { nom: "Garven Metusala", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI9": { nom: "Hannes Delcroix", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI10": { nom: "Leverton Pierre", equipe: "Haiti", groupe: "C", page: 28 },
    "HAI11": { nom: "Danley Jean Jacques", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI12": { nom: "Jean-Ricner Bellegarde", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI13": { nom: "Team Photo", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI14": { nom: "Christopher Attys", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI15": { nom: "Derrick Etienne Jr", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI16": { nom: "Josue Casimir", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI17": { nom: "Ruben Providence", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI18": { nom: "Duckens Nazon", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI19": { nom: "Louicius Deedson", equipe: "Haiti", groupe: "C", page: 29 },
    "HAI20": { nom: "Frantzdy Pierrot", equipe: "Haiti", groupe: "C", page: 29 },
    "SCO1": { nom: "Emblem", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO2": { nom: "Angus Gunn", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO3": { nom: "Jack Hendry", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO4": { nom: "Kieran Tierney", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO5": { nom: "Aaron Hickey", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO6": { nom: "Andrew Robertson", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO7": { nom: "Scott McKenna", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO8": { nom: "John Souttar", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO9": { nom: "Anthony Ralston", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO10": { nom: "Grant Hanley", equipe: "Scotland", groupe: "C", page: 30 },
    "SCO11": { nom: "Scott McTominay", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO12": { nom: "Billy Gilmour", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO13": { nom: "Team Photo", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO14": { nom: "Lewis Ferguson", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO15": { nom: "Ryan Christie", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO16": { nom: "Kenny McLean", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO17": { nom: "John McGinn", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO18": { nom: "Lyndon Dykes", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO19": { nom: "Che Adams", equipe: "Scotland", groupe: "C", page: 31 },
    "SCO20": { nom: "Ben Gannon-Doak", equipe: "Scotland", groupe: "C", page: 31 },
    "USA1": { nom: "Emblem", equipe: "USA", groupe: "D", page: 32 },
    "USA2": { nom: "Math Freese", equipe: "USA", groupe: "D", page: 32 },
    "USA3": { nom: "Chris Richards", equipe: "USA", groupe: "D", page: 32 },
    "USA4": { nom: "Tim Ream", equipe: "USA", groupe: "D", page: 32 },
    "USA5": { nom: "Mark McKenzie", equipe: "USA", groupe: "D", page: 32 },
    "USA6": { nom: "Alex Freeman", equipe: "USA", groupe: "D", page: 32 },
    "USA7": { nom: "Antonee Robinson", equipe: "USA", groupe: "D", page: 32 },
    "USA8": { nom: "Tyler Adams", equipe: "USA", groupe: "D", page: 32 },
    "USA9": { nom: "Tanner Tessmann", equipe: "USA", groupe: "D", page: 32 },
    "USA10": { nom: "Weston McKenny", equipe: "USA", groupe: "D", page: 32 },
    "USA11": { nom: "Christian Roldan", equipe: "USA", groupe: "D", page: 33 },
    "USA12": { nom: "Timothy Weah", equipe: "USA", groupe: "D", page: 33 },
    "USA13": { nom: "Team Photo", equipe: "USA", groupe: "D", page: 33 },
    "USA14": { nom: "Diego Luna", equipe: "USA", groupe: "D", page: 33 },
    "USA15": { nom: "Malik Tillman", equipe: "USA", groupe: "D", page: 33 },
    "USA16": { nom: "Christian Pulisic", equipe: "USA", groupe: "D", page: 33 },
    "USA17": { nom: "Brenden Aaronson", equipe: "USA", groupe: "D", page: 33 },
    "USA18": { nom: "Ricardo Pepi", equipe: "USA", groupe: "D", page: 33 },
    "USA19": { nom: "Haji Wright", equipe: "USA", groupe: "D", page: 33 },
    "USA20": { nom: "Folarin Balogun", equipe: "USA", groupe: "D", page: 33 },
    "PAR1": { nom: "Emblem", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR2": { nom: "Roberto Fernandez", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR3": { nom: "Orlando Gill", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR4": { nom: "Gustavo Gomez", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR5": { nom: "Fabián Balbuena", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR6": { nom: "Juan José Cáceres", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR7": { nom: "Omar Alderete", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR8": { nom: "Junior Alonso", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR9": { nom: "Mathías Villasanti", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR10": { nom: "Diego Gomez", equipe: "Paraguay", groupe: "D", page: 34 },
    "PAR11": { nom: "Damián Bobadilla", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR12": { nom: "Andres Cubas", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR13": { nom: "Team Photo", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR14": { nom: "Matias Galarza Fonda", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR15": { nom: "Julio Enciso", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR16": { nom: "Alejandro Romero Gamarra", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR17": { nom: "Miguel Almirón", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR18": { nom: "Ramon Sosa", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR19": { nom: "Angel Romero", equipe: "Paraguay", groupe: "D", page: 35 },
    "PAR20": { nom: "Antonio Sanabria", equipe: "Paraguay", groupe: "D", page: 35 },
    "AUS1": { nom: "Emblem", equipe: "Australia", groupe: "D", page: 36 },
    "AUS2": { nom: "Mathew Ryan", equipe: "Australia", groupe: "D", page: 36 },
    "AUS3": { nom: "Joe Gauci", equipe: "Australia", groupe: "D", page: 36 },
    "AUS4": { nom: "Harry Souttar", equipe: "Australia", groupe: "D", page: 36 },
    "AUS5": { nom: "Alessandro Circati", equipe: "Australia", groupe: "D", page: 36 },
    "AUS6": { nom: "Jordan Bos", equipe: "Australia", groupe: "D", page: 36 },
    "AUS7": { nom: "Aziz Behich", equipe: "Australia", groupe: "D", page: 36 },
    "AUS8": { nom: "Cameron Burgess", equipe: "Australia", groupe: "D", page: 36 },
    "AUS9": { nom: "Lewis Miller", equipe: "Australia", groupe: "D", page: 36 },
    "AUS10": { nom: "Milos Degenek", equipe: "Australia", groupe: "D", page: 36 },
    "AUS11": { nom: "Jackson Irvine", equipe: "Australia", groupe: "D", page: 37 },
    "AUS12": { nom: "Riley McGree", equipe: "Australia", groupe: "D", page: 37 },
    "AUS13": { nom: "Team Photo", equipe: "Australia", groupe: "D", page: 37 },
    "AUS14": { nom: "Aiden O’Neill", equipe: "Australia", groupe: "D", page: 37 },
    "AUS15": { nom: "Connor Metcalfe", equipe: "Australia", groupe: "D", page: 37 },
    "AUS16": { nom: "Patrick Yazbek", equipe: "Australia", groupe: "D", page: 37 },
    "AUS17": { nom: "Craig Goodwin", equipe: "Australia", groupe: "D", page: 37 },
    "AUS18": { nom: "Kusini Vengi", equipe: "Australia", groupe: "D", page: 37 },
    "AUS19": { nom: "Nestory Irankunda", equipe: "Australia", groupe: "D", page: 37 },
    "AUS20": { nom: "Mohamed Touré", equipe: "Australia", groupe: "D", page: 37 },
    "TUR1": { nom: "Emblem", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR2": { nom: "Ugurcan Cakir", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR3": { nom: "Mert Muldur", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR4": { nom: "Zeki Celik", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR5": { nom: "Abdulkerim Bardakci", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR6": { nom: "Caglar Soyuncu", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR7": { nom: "Merih Demiral", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR8": { nom: "Ferdi Kadioglu", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR9": { nom: "Kaan Ayhan", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR10": { nom: "Ismail Yuksek", equipe: "Türkiye", groupe: "D", page: 38 },
    "TUR11": { nom: "Hakan Calhanoglu", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR12": { nom: "Orkun Kokcu", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR13": { nom: "Team Photo", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR14": { nom: "Arda Guler", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR15": { nom: "Irfan Can Kahveci", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR16": { nom: "Yunus Akgun", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR17": { nom: "Can Uzun", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR18": { nom: "Baris Alper Yilmaz", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR19": { nom: "Kerem Akturkoglu", equipe: "Türkiye", groupe: "D", page: 39 },
    "TUR20": { nom: "Kenan Yildiz", equipe: "Türkiye", groupe: "D", page: 39 },
    "GER1": { nom: "Emblem", equipe: "Germany", groupe: "E", page: 40 },
    "GER2": { nom: "Marc-André ter Stegen", equipe: "Germany", groupe: "E", page: 40 },
    "GER3": { nom: "Jonathan Tah", equipe: "Germany", groupe: "E", page: 40 },
    "GER4": { nom: "David Raum", equipe: "Germany", groupe: "E", page: 40 },
    "GER5": { nom: "Nico Schlotterbeck", equipe: "Germany", groupe: "E", page: 40 },
    "GER6": { nom: "Antonio Rüdiger", equipe: "Germany", groupe: "E", page: 40 },
    "GER7": { nom: "Waldemar Anton", equipe: "Germany", groupe: "E", page: 40 },
    "GER8": { nom: "Ridle Baku", equipe: "Germany", groupe: "E", page: 40 },
    "GER9": { nom: "Maximilian Mittelstadt", equipe: "Germany", groupe: "E", page: 40 },
    "GER10": { nom: "Joshua Kimmich", equipe: "Germany", groupe: "E", page: 40 },
    "GER11": { nom: "Florian Wirtz", equipe: "Germany", groupe: "E", page: 41 },
    "GER12": { nom: "Felix Nmecha", equipe: "Germany", groupe: "E", page: 41 },
    "GER13": { nom: "Team Photo", equipe: "Germany", groupe: "E", page: 41 },
    "GER14": { nom: "Leon Goretzka", equipe: "Germany", groupe: "E", page: 41 },
    "GER15": { nom: "Jamal Musiala", equipe: "Germany", groupe: "E", page: 41 },
    "GER16": { nom: "Serge Gnabry", equipe: "Germany", groupe: "E", page: 41 },
    "GER17": { nom: "Kai Havertz", equipe: "Germany", groupe: "E", page: 41 },
    "GER18": { nom: "Leroy Sane", equipe: "Germany", groupe: "E", page: 41 },
    "GER19": { nom: "Karim Adeyemi", equipe: "Germany", groupe: "E", page: 41 },
    "GER20": { nom: "Nick Woltemade", equipe: "Germany", groupe: "E", page: 41 },
    "CUW1": { nom: "Emblem", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW2": { nom: "Eloy Room", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW3": { nom: "Armando Obispo", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW4": { nom: "Sherel Floranus", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW5": { nom: "Jurien Gaari", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW6": { nom: "Joshua Brenet", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW7": { nom: "Roshon Van Eijma", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW8": { nom: "Shurandy Sambo", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW9": { nom: "Livano Comenencia", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW10": { nom: "Godfried Roemeratoe", equipe: "Curaçao", groupe: "E", page: 42 },
    "CUW11": { nom: "Juninho Bacuna", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW12": { nom: "Leandro Bacuna", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW13": { nom: "Team Photo", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW14": { nom: "Tahith Chong", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW15": { nom: "Kenji Gorre", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW16": { nom: "Jearl Margaritha", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW17": { nom: "Jurgen Locadia", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW18": { nom: "Jeremy Antonisse", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW19": { nom: "Gervane Kastaneer", equipe: "Curaçao", groupe: "E", page: 43 },
    "CUW20": { nom: "Sontje Hansen", equipe: "Curaçao", groupe: "E", page: 43 },
    "CIV1": { nom: "Emblem", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV2": { nom: "Yahia Fofana", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV3": { nom: "Ghislain Konan", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV4": { nom: "Wilfried Singo", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV5": { nom: "Odilon Kossounou", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV6": { nom: "Evan Ndicka", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV7": { nom: "Willy Boly", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV8": { nom: "Emmanuel Agbadou", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV9": { nom: "Ousmane Diomande", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV10": { nom: "Franck Kessie", equipe: "Ivory Coast", groupe: "E", page: 44 },
    "CIV11": { nom: "Seko Fofana", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV12": { nom: "Ibrahim Sangare", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV13": { nom: "Team Photo", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV14": { nom: "Jean-Philippe Gbamin", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV15": { nom: "Amad Diallo", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV16": { nom: "Sébastien Haller", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV17": { nom: "Simon Adingra", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV18": { nom: "Yan Diomande", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV19": { nom: "Evann Guessand", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "CIV20": { nom: "Oumar Diakite", equipe: "Ivory Coast", groupe: "E", page: 45 },
    "ECU1": { nom: "Emblem", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU2": { nom: "Hernán Galíndez", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU3": { nom: "Gonzalo Valle", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU4": { nom: "Piero Hincapié", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU5": { nom: "Pervis Estupiñán", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU6": { nom: "Willian Pacho", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU7": { nom: "Ángelo Preciado", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU8": { nom: "Joel Ordóñez", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU9": { nom: "Moises Caicedo", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU10": { nom: "Alan Franco", equipe: "Ecuador", groupe: "E", page: 46 },
    "ECU11": { nom: "Kendry Paez", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU12": { nom: "Pedro Vite", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU13": { nom: "Team Photo", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU14": { nom: "John Veboah", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU15": { nom: "Leonardo Campana", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU16": { nom: "Gonzalo Plata", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU17": { nom: "Nilson Angulo", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU18": { nom: "Alan Minda", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU19": { nom: "Kevin Rodriguez", equipe: "Ecuador", groupe: "E", page: 47 },
    "ECU20": { nom: "Enner Valencia", equipe: "Ecuador", groupe: "E", page: 47 },
    "NED1": { nom: "Emblem", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED2": { nom: "Bart Verbruggen", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED3": { nom: "Virgil van Dijk", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED4": { nom: "Micky van de Ven", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED5": { nom: "Jurrien Timber", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED6": { nom: "Denzel Dumfries", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED7": { nom: "Nathan Aké", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED8": { nom: "Jeremie Frimpong", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED9": { nom: "Jan Paul van Hecke", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED10": { nom: "Tijjani Reijnders", equipe: "Netherlands", groupe: "F", page: 48 },
    "NED11": { nom: "Ryan Gravenberch", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED12": { nom: "Teun Koopmeiners", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED13": { nom: "Team Photo", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED14": { nom: "Frenkie de Jong", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED15": { nom: "Xavi Simons", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED16": { nom: "Justin Kluivert", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED17": { nom: "Memphis Depay", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED18": { nom: "Donyell Malen", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED19": { nom: "Wout Weghorst", equipe: "Netherlands", groupe: "F", page: 49 },
    "NED20": { nom: "Cody Gakpo", equipe: "Netherlands", groupe: "F", page: 49 },
    "JPN1": { nom: "Emblem", equipe: "Japan", groupe: "F", page: 50 },
    "JPN2": { nom: "Zion Suzuki", equipe: "Japan", groupe: "F", page: 50 },
    "JPN3": { nom: "Henry Heroki Mochizuki", equipe: "Japan", groupe: "F", page: 50 },
    "JPN4": { nom: "Ayumu Seko", equipe: "Japan", groupe: "F", page: 50 },
    "JPN5": { nom: "Junnosuke Suzuki", equipe: "Japan", groupe: "F", page: 50 },
    "JPN6": { nom: "Shogo Taniguchi", equipe: "Japan", groupe: "F", page: 50 },
    "JPN7": { nom: "Tsuyoshi Watanabe", equipe: "Japan", groupe: "F", page: 50 },
    "JPN8": { nom: "Kaishu Sano", equipe: "Japan", groupe: "F", page: 50 },
    "JPN9": { nom: "Yuki Soma", equipe: "Japan", groupe: "F", page: 50 },
    "JPN10": { nom: "Ao Tanaka", equipe: "Japan", groupe: "F", page: 50 },
    "JPN11": { nom: "Daichi Kamada", equipe: "Japan", groupe: "F", page: 51 },
    "JPN12": { nom: "Takefusa Kubo", equipe: "Japan", groupe: "F", page: 51 },
    "JPN13": { nom: "Team Photo", equipe: "Japan", groupe: "F", page: 51 },
    "JPN14": { nom: "Ritsu Doan", equipe: "Japan", groupe: "F", page: 51 },
    "JPN15": { nom: "Keito Nakamura", equipe: "Japan", groupe: "F", page: 51 },
    "JPN16": { nom: "Takumi Minamino", equipe: "Japan", groupe: "F", page: 51 },
    "JPN17": { nom: "Shuto Machino", equipe: "Japan", groupe: "F", page: 51 },
    "JPN18": { nom: "Junya Ito", equipe: "Japan", groupe: "F", page: 51 },
    "JPN19": { nom: "Koki Ogawa", equipe: "Japan", groupe: "F", page: 51 },
    "JPN20": { nom: "Ayase Ueda", equipe: "Japan", groupe: "F", page: 51 },
    "SWE1": { nom: "Emblem", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE2": { nom: "Victor Johansson", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE3": { nom: "Isak Hien", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE4": { nom: "Gabriel Gudmundsson", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE5": { nom: "Emil Holm", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE6": { nom: "Victor Nilsson Lindelöf", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE7": { nom: "Gustaf Lagerbielke", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE8": { nom: "Lucas Bergvall", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE9": { nom: "Hugo Larsson", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE10": { nom: "Jesper Karlström", equipe: "Sweden", groupe: "F", page: 52 },
    "SWE11": { nom: "Yasin Ayari", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE12": { nom: "Mattias Svanberg", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE13": { nom: "Team Photo", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE14": { nom: "Daniel Svensson", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE15": { nom: "Ken Sema", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE16": { nom: "Roony Bardghji", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE17": { nom: "Dejan Kulusevski", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE18": { nom: "Anthony Elanga", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE19": { nom: "Alexander Isak", equipe: "Sweden", groupe: "F", page: 53 },
    "SWE20": { nom: "Viktor Gyökeres", equipe: "Sweden", groupe: "F", page: 53 },
    "TUN1": { nom: "Emblem", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN2": { nom: "Bechir Ben Said", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN3": { nom: "Aymen Dahmen", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN4": { nom: "Yan Valery", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN5": { nom: "Montassar Talbi", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN6": { nom: "Yassine Meriah", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN7": { nom: "Ali Abdi", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN8": { nom: "Dylan Bronn", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN9": { nom: "Ellyes Skhiri", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN10": { nom: "Aissa Laidouni", equipe: "Tunisia", groupe: "F", page: 54 },
    "TUN11": { nom: "Ferjani Sassi", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN12": { nom: "Mohamed Ali Ben Romdhane", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN13": { nom: "Team Photo", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN14": { nom: "Hannibal Mejbri", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN15": { nom: "Elias Achouri", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN16": { nom: "Elias Saad", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN17": { nom: "Hazem Mastouri", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN18": { nom: "Ismael Gharbi", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN19": { nom: "Sayfallah Ltaief", equipe: "Tunisia", groupe: "F", page: 55 },
    "TUN20": { nom: "Naim Sliti", equipe: "Tunisia", groupe: "F", page: 55 },
    "BEL1": { nom: "Emblem", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL2": { nom: "Thibaut Courtois", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL3": { nom: "Arthur Theate", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL4": { nom: "Timothy Castagne", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL5": { nom: "Zeno Debast", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL6": { nom: "Brandon Mechele", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL7": { nom: "Maxim De Cuyper", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL8": { nom: "Thomas Meunier", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL9": { nom: "Youri Tielemans", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL10": { nom: "Amadou Onana", equipe: "Belgium", groupe: "G", page: 58 },
    "BEL11": { nom: "Nicolas Raskin", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL12": { nom: "Alexis Saelemaekers", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL13": { nom: "Team Photo", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL14": { nom: "Hans Vanaken", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL15": { nom: "Kevin De Bruyne", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL16": { nom: "Jérémy Doku", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL17": { nom: "Charles De Ketelaere", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL18": { nom: "Leandro Trossard", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL19": { nom: "Loïs Openda", equipe: "Belgium", groupe: "G", page: 59 },
    "BEL20": { nom: "Romelu Lukaku", equipe: "Belgium", groupe: "G", page: 59 },
    "EGY1": { nom: "Emblem", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY2": { nom: "Mohamed El Shenawy", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY3": { nom: "Mohamed Hany", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY4": { nom: "Mohamed Hamdy", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY5": { nom: "Yasser Ibrahim", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY6": { nom: "Khaled Sobhi", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY7": { nom: "Ramy Rabia", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY8": { nom: "Hossam Abdelmaguid", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY9": { nom: "Ahmed Fatouh", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY10": { nom: "Marwan Attia", equipe: "Egypt", groupe: "G", page: 60 },
    "EGY11": { nom: "Zizo", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY12": { nom: "Hamdy Fathy", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY13": { nom: "Team Photo", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY14": { nom: "Mohamed Lasheen", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY15": { nom: "Emam Ashour", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY16": { nom: "Osama Faisal", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY17": { nom: "Mohamed Salah", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY18": { nom: "Mostafa Mohamed", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY19": { nom: "Trezeguet", equipe: "Egypt", groupe: "G", page: 61 },
    "EGY20": { nom: "Omar Marmoush", equipe: "Egypt", groupe: "G", page: 61 },
    "IRN1": { nom: "Emblem", equipe: "Iran", groupe: "G", page: 62 },
    "IRN2": { nom: "Alireza Beiranvand", equipe: "Iran", groupe: "G", page: 62 },
    "IRN3": { nom: "Morteza Pouraliganji", equipe: "Iran", groupe: "G", page: 62 },
    "IRN4": { nom: "Ehsan Hajsafi", equipe: "Iran", groupe: "G", page: 62 },
    "IRN5": { nom: "Milad Mohammadi", equipe: "Iran", groupe: "G", page: 62 },
    "IRN6": { nom: "Shojae Khalilzadeh", equipe: "Iran", groupe: "G", page: 62 },
    "IRN7": { nom: "Ramin Rezaeian", equipe: "Iran", groupe: "G", page: 62 },
    "IRN8": { nom: "Hossein Kanaani", equipe: "Iran", groupe: "G", page: 62 },
    "IRN9": { nom: "Sadegh Moharrami", equipe: "Iran", groupe: "G", page: 62 },
    "IRN10": { nom: "Saleh Hardani", equipe: "Iran", groupe: "G", page: 62 },
    "IRN11": { nom: "Saeed Ezatolahi", equipe: "Iran", groupe: "G", page: 63 },
    "IRN12": { nom: "Saman Ghoddos", equipe: "Iran", groupe: "G", page: 63 },
    "IRN13": { nom: "Team Photo", equipe: "Iran", groupe: "G", page: 63 },
    "IRN14": { nom: "Omid Noorafkan", equipe: "Iran", groupe: "G", page: 63 },
    "IRN15": { nom: "Roozbeh Cheshmi", equipe: "Iran", groupe: "G", page: 63 },
    "IRN16": { nom: "Mohammad Mohebi", equipe: "Iran", groupe: "G", page: 63 },
    "IRN17": { nom: "Sardar Azmoun", equipe: "Iran", groupe: "G", page: 63 },
    "IRN18": { nom: "Mehdi Taremi", equipe: "Iran", groupe: "G", page: 63 },
    "IRN19": { nom: "Alireza Jahanbakhsh", equipe: "Iran", groupe: "G", page: 63 },
    "IRN20": { nom: "Ali Gholizadeh", equipe: "Iran", groupe: "G", page: 63 },
    "NZL1": { nom: "Emblem", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL2": { nom: "Max Crocombe Payne", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL3": { nom: "Alex Paulsen", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL4": { nom: "Michael Boxall", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL5": { nom: "Liberato Cacace", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL6": { nom: "Tim Payne", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL7": { nom: "Tyler Bindon", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL8": { nom: "Francis de Vries", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL9": { nom: "Finn Surman", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL10": { nom: "Joe Bell", equipe: "New Zealand", groupe: "G", page: 64 },
    "NZL11": { nom: "Sarpreet Singh", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL12": { nom: "Ryan Thomas", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL13": { nom: "Team Photo", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL14": { nom: "Matthew Garbett", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL15": { nom: "Marko Stamenić", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL16": { nom: "Ben Old", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL17": { nom: "Chris Wood", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL18": { nom: "Elijah Just", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL19": { nom: "Callum McCowatt", equipe: "New Zealand", groupe: "G", page: 65 },
    "NZL20": { nom: "Kosta Barbarouses", equipe: "New Zealand", groupe: "G", page: 65 },
    "ESP1": { nom: "Emblem", equipe: "Spain", groupe: "H", page: 66 },
    "ESP2": { nom: "Unai Simon", equipe: "Spain", groupe: "H", page: 66 },
    "ESP3": { nom: "Robin Le Normand", equipe: "Spain", groupe: "H", page: 66 },
    "ESP4": { nom: "Aymeric Laporte", equipe: "Spain", groupe: "H", page: 66 },
    "ESP5": { nom: "Dean Huijsen", equipe: "Spain", groupe: "H", page: 66 },
    "ESP6": { nom: "Pedro Porro", equipe: "Spain", groupe: "H", page: 66 },
    "ESP7": { nom: "Dani Carvajal", equipe: "Spain", groupe: "H", page: 66 },
    "ESP8": { nom: "Marc Cucurella", equipe: "Spain", groupe: "H", page: 66 },
    "ESP9": { nom: "Martín Zubimendi", equipe: "Spain", groupe: "H", page: 66 },
    "ESP10": { nom: "Rodri", equipe: "Spain", groupe: "H", page: 66 },
    "ESP11": { nom: "Pedri", equipe: "Spain", groupe: "H", page: 67 },
    "ESP12": { nom: "Fabian Ruiz", equipe: "Spain", groupe: "H", page: 67 },
    "ESP13": { nom: "Team Photo", equipe: "Spain", groupe: "H", page: 67 },
    "ESP14": { nom: "Mikel Merino", equipe: "Spain", groupe: "H", page: 67 },
    "ESP15": { nom: "Lamine Yamal", equipe: "Spain", groupe: "H", page: 67 },
    "ESP16": { nom: "Dani Olmo", equipe: "Spain", groupe: "H", page: 67 },
    "ESP17": { nom: "Nico Williams", equipe: "Spain", groupe: "H", page: 67 },
    "ESP18": { nom: "Ferran Torres", equipe: "Spain", groupe: "H", page: 67 },
    "ESP19": { nom: "Álvaro Morata", equipe: "Spain", groupe: "H", page: 67 },
    "ESP20": { nom: "Mikel Oyarzabal", equipe: "Spain", groupe: "H", page: 67 },
    "CPV1": { nom: "Emblem", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV2": { nom: "Vozinha", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV3": { nom: "Logan Costa", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV4": { nom: "Pico", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV5": { nom: "Diney", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV6": { nom: "Steven Moreira", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV7": { nom: "Wagner Pina", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV8": { nom: "Joao Paulo", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV9": { nom: "Yannick Semedo", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV10": { nom: "Kevin Pina", equipe: "Cape Verde", groupe: "H", page: 68 },
    "CPV11": { nom: "Patrick Andrade", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV12": { nom: "Jamiro Monteiro", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV13": { nom: "Team Photo", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV14": { nom: "Deroy Duarte", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV15": { nom: "Garry Rodrigues", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV16": { nom: "Jovane Cabral", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV17": { nom: "Ryan Mendes", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV18": { nom: "Dailon Livramento", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV19": { nom: "Willy Semedo", equipe: "Cape Verde", groupe: "H", page: 69 },
    "CPV20": { nom: "Bebe", equipe: "Cape Verde", groupe: "H", page: 69 },
    "KSA1": { nom: "Emblem", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA2": { nom: "Nawaf Alaqidi", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA3": { nom: "Abdulrahman Al-Sanbi", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA4": { nom: "Saud Abdulhamid", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA5": { nom: "Nawaf Bouwashl", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA6": { nom: "Jihad Thakri", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA7": { nom: "Moteb Al-Harbi", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA8": { nom: "Hassan Altambakti", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA9": { nom: "Musab Aljuwayr", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA10": { nom: "Ziyad Aljohani", equipe: "Saudi Arabia", groupe: "H", page: 70 },
    "KSA11": { nom: "Abdullah Alkhaibari", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA12": { nom: "Nasser Aldawsari", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA13": { nom: "Team Photo", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA14": { nom: "Saleh Abu Alshamat", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA15": { nom: "Marwan Alsahafi", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA16": { nom: "Salem Aldawsari", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA17": { nom: "Abdulrahman Al-Aboud", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA18": { nom: "Feras Akbrikan", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA19": { nom: "Saleh Alshehri", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "KSA20": { nom: "Abdullah Al-Hamdan", equipe: "Saudi Arabia", groupe: "H", page: 71 },
    "URU1": { nom: "Emblem", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU2": { nom: "Sergio Rochet", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU3": { nom: "Santiago Mele", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU4": { nom: "Ronald Araujo", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU5": { nom: "José María Giménez", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU6": { nom: "Sebastian Caceres", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU7": { nom: "Mathias Olivera", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU8": { nom: "Guillermo Varela", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU9": { nom: "Nahitan Nandez", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU10": { nom: "Federico Valverde", equipe: "Uruguay", groupe: "H", page: 72 },
    "URU11": { nom: "Giorgian De Arrascaeta", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU12": { nom: "Rodrigo Bentancur", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU13": { nom: "Team Photo", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU14": { nom: "Manuel Ugarte", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU15": { nom: "Nicolás de la Cruz", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU16": { nom: "Maxi Araujo", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU17": { nom: "Darwin Núñez", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU18": { nom: "Federico Viñas", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU19": { nom: "Rodrigo Aguirre", equipe: "Uruguay", groupe: "H", page: 73 },
    "URU20": { nom: "Facundo Pellistri", equipe: "Uruguay", groupe: "H", page: 73 },
    "FRA1": { nom: "Emblem", equipe: "France", groupe: "I", page: 74 },
    "FRA2": { nom: "Mike Maignan", equipe: "France", groupe: "I", page: 74 },
    "FRA3": { nom: "Theo Hernandez", equipe: "France", groupe: "I", page: 74 },
    "FRA4": { nom: "William Saliba", equipe: "France", groupe: "I", page: 74 },
    "FRA5": { nom: "Jules Kounde", equipe: "France", groupe: "I", page: 74 },
    "FRA6": { nom: "Ibrahima Konate", equipe: "France", groupe: "I", page: 74 },
    "FRA7": { nom: "Dayot Upamecano", equipe: "France", groupe: "I", page: 74 },
    "FRA8": { nom: "Lucas Digne", equipe: "France", groupe: "I", page: 74 },
    "FRA9": { nom: "Aurélien Tchouaméni", equipe: "France", groupe: "I", page: 74 },
    "FRA10": { nom: "Eduardo Camavinga", equipe: "France", groupe: "I", page: 74 },
    "FRA11": { nom: "Manu Kone", equipe: "France", groupe: "I", page: 75 },
    "FRA12": { nom: "Adrien Rabiot", equipe: "France", groupe: "I", page: 75 },
    "FRA13": { nom: "Team Photo", equipe: "France", groupe: "I", page: 75 },
    "FRA14": { nom: "Michael Olise", equipe: "France", groupe: "I", page: 75 },
    "FRA15": { nom: "Ousmane Dembele", equipe: "France", groupe: "I", page: 75 },
    "FRA16": { nom: "Bradley Barcola", equipe: "France", groupe: "I", page: 75 },
    "FRA17": { nom: "Désiré Doué", equipe: "France", groupe: "I", page: 75 },
    "FRA18": { nom: "Kingsley Coman", equipe: "France", groupe: "I", page: 75 },
    "FRA19": { nom: "Hugo Ekitike", equipe: "France", groupe: "I", page: 75 },
    "FRA20": { nom: "Kylian Mbappe", equipe: "France", groupe: "I", page: 75 },
    "SEN1": { nom: "Emblem", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN2": { nom: "Edouard Mendy", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN3": { nom: "Yehvann Diouf", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN4": { nom: "Moussa Niakhaté", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN5": { nom: "Abdoulaye Seck", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN6": { nom: "Ismail Jakobs", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN7": { nom: "El Hadji Malick Diouf", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN8": { nom: "Kalidou Koulibaly", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN9": { nom: "Idrissa Gana Gueye", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN10": { nom: "Pape Matar Sarr", equipe: "Senegal", groupe: "I", page: 76 },
    "SEN11": { nom: "Pape Gueye", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN12": { nom: "Habib Diarra", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN13": { nom: "Team Photo", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN14": { nom: "Lamine Camara", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN15": { nom: "Sadio Mane", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN16": { nom: "Ismaïla Sarr", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN17": { nom: "Boulaye Dia", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN18": { nom: "Iliman Ndiaye", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN19": { nom: "Nicolas Jackson", equipe: "Senegal", groupe: "I", page: 77 },
    "SEN20": { nom: "Krepin Diatta", equipe: "Senegal", groupe: "I", page: 77 },
    "IRQ1": { nom: "Emblem", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ2": { nom: "Jalal Hassan", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ3": { nom: "Rebin Sulaka", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ4": { nom: "Hussein Ali", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ5": { nom: "Akam Hashem", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ6": { nom: "Merchas Doski", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ7": { nom: "Zaid Tahseen", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ8": { nom: "Manaf Younis", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ9": { nom: "Zidane Iqbal", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ10": { nom: "Amir Al-Ammari", equipe: "Iraq", groupe: "I", page: 78 },
    "IRQ11": { nom: "Ibrahim Bavesh", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ12": { nom: "Ali Jasim", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ13": { nom: "Team Photo", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ14": { nom: "Youssef Amyn", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ15": { nom: "Aimar Sher", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ16": { nom: "Marko Farji", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ17": { nom: "Osama Rashid", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ18": { nom: "Ali Al-Hamadi", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ19": { nom: "Aymen Hussein", equipe: "Iraq", groupe: "I", page: 79 },
    "IRQ20": { nom: "Mohanad Ali", equipe: "Iraq", groupe: "I", page: 79 },
    "NOR1": { nom: "Emblem", equipe: "Norway", groupe: "I", page: 80 },
    "NOR2": { nom: "Orjan Nyland", equipe: "Norway", groupe: "I", page: 80 },
    "NOR3": { nom: "Julian Ryerson", equipe: "Norway", groupe: "I", page: 80 },
    "NOR4": { nom: "Leo Ostigård", equipe: "Norway", groupe: "I", page: 80 },
    "NOR5": { nom: "Kristoffer Vassbakk Ajer", equipe: "Norway", groupe: "I", page: 80 },
    "NOR6": { nom: "Marcus Holmgren Pedersen", equipe: "Norway", groupe: "I", page: 80 },
    "NOR7": { nom: "David Møller Wolfe", equipe: "Norway", groupe: "I", page: 80 },
    "NOR8": { nom: "Torbjørn Heggem", equipe: "Norway", groupe: "I", page: 80 },
    "NOR9": { nom: "Morten Thorsby", equipe: "Norway", groupe: "I", page: 80 },
    "NOR10": { nom: "Martin Ødegaard", equipe: "Norway", groupe: "I", page: 80 },
    "NOR11": { nom: "Sander Berge", equipe: "Norway", groupe: "I", page: 81 },
    "NOR12": { nom: "Andreas Schjelderup", equipe: "Norway", groupe: "I", page: 81 },
    "NOR13": { nom: "Team Photo", equipe: "Norway", groupe: "I", page: 81 },
    "NOR14": { nom: "Patrick Berg", equipe: "Norway", groupe: "I", page: 81 },
    "NOR15": { nom: "Erling Haaland", equipe: "Norway", groupe: "I", page: 81 },
    "NOR16": { nom: "Alexander Sørloth", equipe: "Norway", groupe: "I", page: 81 },
    "NOR17": { nom: "Aron Dønnum", equipe: "Norway", groupe: "I", page: 81 },
    "NOR18": { nom: "Jorgen Strand Larsen", equipe: "Norway", groupe: "I", page: 81 },
    "NOR19": { nom: "Antonio Nusa", equipe: "Norway", groupe: "I", page: 81 },
    "NOR20": { nom: "Oscar Bobb", equipe: "Norway", groupe: "I", page: 81 },
    "ARG1": { nom: "Emblem", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG2": { nom: "Emiliano Martinez", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG3": { nom: "Nahuel Molina", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG4": { nom: "Cristian Romero", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG5": { nom: "Nicolas Otamendi", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG6": { nom: "Nicolas Tagliafico", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG7": { nom: "Leonardo Balerdi", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG8": { nom: "Enzo Fernandez", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG9": { nom: "Alexis Mac Allister", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG10": { nom: "Rodrigo De Paul", equipe: "Argentina", groupe: "J", page: 82 },
    "ARG11": { nom: "Exequiel Palacios", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG12": { nom: "Leandro Paredes", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG13": { nom: "Team Photo", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG14": { nom: "Nico Paz", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG15": { nom: "Franco Mastantuono", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG16": { nom: "Nico Gonzalez", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG17": { nom: "Lionel Messi", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG18": { nom: "Lautaro Martinez", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG19": { nom: "Julian Alvarez", equipe: "Argentina", groupe: "J", page: 83 },
    "ARG20": { nom: "Giuliano Simeone", equipe: "Argentina", groupe: "J", page: 83 },
    "ALG1": { nom: "Emblem", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG2": { nom: "Alexis Guendouz", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG3": { nom: "Ramy Bensebaini", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG4": { nom: "Youcef Atal", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG5": { nom: "Rayan Aït-Nouri", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG6": { nom: "Mohamed Amine Tougai", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG7": { nom: "Aïssa Mandi", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG8": { nom: "Ismael Bennacer", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG9": { nom: "Houssem Aquar", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG10": { nom: "Hicham Boudaoui", equipe: "Algeria", groupe: "J", page: 84 },
    "ALG11": { nom: "Ramiz Zerrouki", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG12": { nom: "Nabil Bentalab", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG13": { nom: "Team Photo", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG14": { nom: "Farés Chaibi", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG15": { nom: "Riyad Mahrez", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG16": { nom: "Said Benrahma", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG17": { nom: "Anis Hadj Moussa", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG18": { nom: "Amine Gouiri", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG19": { nom: "Baghdad Bounedjah", equipe: "Algeria", groupe: "J", page: 85 },
    "ALG20": { nom: "Mohammed Amoura", equipe: "Algeria", groupe: "J", page: 85 },
    "AUT1": { nom: "Emblem", equipe: "Austria", groupe: "J", page: 86 },
    "AUT2": { nom: "Alexander Schlager", equipe: "Austria", groupe: "J", page: 86 },
    "AUT3": { nom: "Patrick Pentz", equipe: "Austria", groupe: "J", page: 86 },
    "AUT4": { nom: "David Alaba", equipe: "Austria", groupe: "J", page: 86 },
    "AUT5": { nom: "Kevin Danso", equipe: "Austria", groupe: "J", page: 86 },
    "AUT6": { nom: "Philipp Lienhart", equipe: "Austria", groupe: "J", page: 86 },
    "AUT7": { nom: "Stefan Posch", equipe: "Austria", groupe: "J", page: 86 },
    "AUT8": { nom: "Phillipp Mwene", equipe: "Austria", groupe: "J", page: 86 },
    "AUT9": { nom: "Alexander Prass", equipe: "Austria", groupe: "J", page: 86 },
    "AUT10": { nom: "Xaver Schlager", equipe: "Austria", groupe: "J", page: 86 },
    "AUT11": { nom: "Marcel Sabitzer", equipe: "Austria", groupe: "J", page: 87 },
    "AUT12": { nom: "Konrad Laimer", equipe: "Austria", groupe: "J", page: 87 },
    "AUT13": { nom: "Team Photo", equipe: "Austria", groupe: "J", page: 87 },
    "AUT14": { nom: "Florian Grillitsch", equipe: "Austria", groupe: "J", page: 87 },
    "AUT15": { nom: "Nicolas Seiwald", equipe: "Austria", groupe: "J", page: 87 },
    "AUT16": { nom: "Romano Schmid", equipe: "Austria", groupe: "J", page: 87 },
    "AUT17": { nom: "Patrick Wimmer", equipe: "Austria", groupe: "J", page: 87 },
    "AUT18": { nom: "Christoph Baumgartner", equipe: "Austria", groupe: "J", page: 87 },
    "AUT19": { nom: "Michael Gregoritsch", equipe: "Austria", groupe: "J", page: 87 },
    "AUT20": { nom: "Marko Arnautović", equipe: "Austria", groupe: "J", page: 87 },
    "JOR1": { nom: "Emblem", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR2": { nom: "Yazeed Abulaila", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR3": { nom: "Ihsan Haddad", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR4": { nom: "Mohammad Abu Hashish", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR5": { nom: "Yazan Al-Arab", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR6": { nom: "Abdallah Nasib", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR7": { nom: "Saleem Obaid", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR8": { nom: "Mohammad Abualnadi", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR9": { nom: "Ibrahim Saadeh", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR10": { nom: "Nizar Al-Rashdan", equipe: "Jordan", groupe: "J", page: 88 },
    "JOR11": { nom: "Noor Al-Rawabdeh", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR12": { nom: "Mohannad Abu Taha", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR13": { nom: "Team Photo", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR14": { nom: "Amer Jamous", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR15": { nom: "Musa Al-Taamari", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR16": { nom: "Yazan Al-Naimat", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR17": { nom: "Mahmoud Al-Mardi", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR18": { nom: "Ali Olwan", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR19": { nom: "Mohammad Abu Zrayq", equipe: "Jordan", groupe: "J", page: 89 },
    "JOR20": { nom: "Ibrahim Sabra", equipe: "Jordan", groupe: "J", page: 89 },
    "POR1": { nom: "Emblem", equipe: "Portugal", groupe: "K", page: 90 },
    "POR2": { nom: "Diogo Costa", equipe: "Portugal", groupe: "K", page: 90 },
    "POR3": { nom: "Jose Sa", equipe: "Portugal", groupe: "K", page: 90 },
    "POR4": { nom: "Ruben Dias", equipe: "Portugal", groupe: "K", page: 90 },
    "POR5": { nom: "João Cancelo", equipe: "Portugal", groupe: "K", page: 90 },
    "POR6": { nom: "Diogo Dalot", equipe: "Portugal", groupe: "K", page: 90 },
    "POR7": { nom: "Nuno Mendes", equipe: "Portugal", groupe: "K", page: 90 },
    "POR8": { nom: "Gonçalo Inácio", equipe: "Portugal", groupe: "K", page: 90 },
    "POR9": { nom: "Bernardo Silva", equipe: "Portugal", groupe: "K", page: 90 },
    "POR10": { nom: "Bruno Fernandes", equipe: "Portugal", groupe: "K", page: 90 },
    "POR11": { nom: "Ruben Neves", equipe: "Portugal", groupe: "K", page: 91 },
    "POR12": { nom: "Vitinha", equipe: "Portugal", groupe: "K", page: 91 },
    "POR13": { nom: "Team Photo", equipe: "Portugal", groupe: "K", page: 91 },
    "POR14": { nom: "João Neves", equipe: "Portugal", groupe: "K", page: 91 },
    "POR15": { nom: "Cristiano Ronaldo", equipe: "Portugal", groupe: "K", page: 91 },
    "POR16": { nom: "Francisco Trincao", equipe: "Portugal", groupe: "K", page: 91 },
    "POR17": { nom: "João Felix", equipe: "Portugal", groupe: "K", page: 91 },
    "POR18": { nom: "Gonçalo Ramos", equipe: "Portugal", groupe: "K", page: 91 },
    "POR19": { nom: "Pedro Neto", equipe: "Portugal", groupe: "K", page: 91 },
    "POR20": { nom: "Rafael Leão", equipe: "Portugal", groupe: "K", page: 91 },
    "COD1": { nom: "Emblem", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD2": { nom: "Lionel Mpasi", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD3": { nom: "Aaron Wan-Bissaka", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD4": { nom: "Axel Tuanzebe", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD5": { nom: "Arthur Masuaku", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD6": { nom: "Chancel Mbemba", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD7": { nom: "Joris Kayembe", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD8": { nom: "Charles Pickel", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD9": { nom: "Ngal’ayel Mukau", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD10": { nom: "Edo Kayembe", equipe: "Congo DR", groupe: "K", page: 92 },
    "COD11": { nom: "Samuel Moutoussamy", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD12": { nom: "Noah Sadiki", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD13": { nom: "Team Photo", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD14": { nom: "Théo Bongonda", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD15": { nom: "Meschak Elia", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD16": { nom: "Yoane Wissa", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD17": { nom: "Brian Cipenga", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD18": { nom: "Fiston Mayele", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD19": { nom: "Cédric Bakambu", equipe: "Congo DR", groupe: "K", page: 93 },
    "COD20": { nom: "Nathanaël Mbuku", equipe: "Congo DR", groupe: "K", page: 93 },
    "UZB1": { nom: "Emblem", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB2": { nom: "Utkir Yusupov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB3": { nom: "Farrukh Savfiev", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB4": { nom: "Sherzod Nasrullaev", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB5": { nom: "Umar Eshmurodov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB6": { nom: "Husniddin Aliqulov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB7": { nom: "Rustamjon Ashurmatov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB8": { nom: "Khojiakbar Alijonov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB9": { nom: "Abdukodir Khusanov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB10": { nom: "Odiljon Hamrobekov", equipe: "Uzbekistan", groupe: "K", page: 94 },
    "UZB11": { nom: "Otabek Shukurov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB12": { nom: "Jamshid Iskanderov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB13": { nom: "Team Photo", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB14": { nom: "Azizbek Turgunboev", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB15": { nom: "Khojimat Erkinov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB16": { nom: "Eldor Shomurodov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB17": { nom: "Oston Urunov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB18": { nom: "Jaloliddin Masharipov", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB19": { nom: "Igor Sergeev", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "UZB20": { nom: "Abbosbek Fayzullaev", equipe: "Uzbekistan", groupe: "K", page: 95 },
    "COL1": { nom: "Emblem", equipe: "Colombia", groupe: "K", page: 96 },
    "COL2": { nom: "Camilo Vargas", equipe: "Colombia", groupe: "K", page: 96 },
    "COL3": { nom: "David Ospina", equipe: "Colombia", groupe: "K", page: 96 },
    "COL4": { nom: "Dávinson Sánchez", equipe: "Colombia", groupe: "K", page: 96 },
    "COL5": { nom: "Yerry Mina", equipe: "Colombia", groupe: "K", page: 96 },
    "COL6": { nom: "Daniel Munoz", equipe: "Colombia", groupe: "K", page: 96 },
    "COL7": { nom: "Johan Mojica", equipe: "Colombia", groupe: "K", page: 96 },
    "COL8": { nom: "Jhon Lucumí", equipe: "Colombia", groupe: "K", page: 96 },
    "COL9": { nom: "Santiago Arias", equipe: "Colombia", groupe: "K", page: 96 },
    "COL10": { nom: "Jefferson Lerma", equipe: "Colombia", groupe: "K", page: 96 },
    "COL11": { nom: "Kevin Castaño", equipe: "Colombia", groupe: "K", page: 97 },
    "COL12": { nom: "Richard Rios", equipe: "Colombia", groupe: "K", page: 97 },
    "COL13": { nom: "Team Photo", equipe: "Colombia", groupe: "K", page: 97 },
    "COL14": { nom: "James Rodriguez", equipe: "Colombia", groupe: "K", page: 97 },
    "COL15": { nom: "Juan Fernando Quintero", equipe: "Colombia", groupe: "K", page: 97 },
    "COL16": { nom: "Jorge Carrascal", equipe: "Colombia", groupe: "K", page: 97 },
    "COL17": { nom: "Jon Arias", equipe: "Colombia", groupe: "K", page: 97 },
    "COL18": { nom: "Jhon Cordova", equipe: "Colombia", groupe: "K", page: 97 },
    "COL19": { nom: "Luis Suarez", equipe: "Colombia", groupe: "K", page: 97 },
    "COL20": { nom: "Luis Diaz", equipe: "Colombia", groupe: "K", page: 97 },
    "ENG1": { nom: "Emblem", equipe: "England", groupe: "L", page: 98 },
    "ENG2": { nom: "Jordan Pickford", equipe: "England", groupe: "L", page: 98 },
    "ENG3": { nom: "John Stones", equipe: "England", groupe: "L", page: 98 },
    "ENG4": { nom: "Marc Guéhi", equipe: "England", groupe: "L", page: 98 },
    "ENG5": { nom: "Ezri Konsa", equipe: "England", groupe: "L", page: 98 },
    "ENG6": { nom: "Trent Alexander-Arnold", equipe: "England", groupe: "L", page: 98 },
    "ENG7": { nom: "Reece James", equipe: "England", groupe: "L", page: 98 },
    "ENG8": { nom: "Dan Burn", equipe: "England", groupe: "L", page: 98 },
    "ENG9": { nom: "Jordan Henderson", equipe: "England", groupe: "L", page: 98 },
    "ENG10": { nom: "Declan Rice", equipe: "England", groupe: "L", page: 98 },
    "ENG11": { nom: "Jude Bellingham", equipe: "England", groupe: "L", page: 99 },
    "ENG12": { nom: "Cole Palmer", equipe: "England", groupe: "L", page: 99 },
    "ENG13": { nom: "Team Photo", equipe: "England", groupe: "L", page: 99 },
    "ENG14": { nom: "Morgan Rogers", equipe: "England", groupe: "L", page: 99 },
    "ENG15": { nom: "Anthony Gordon", equipe: "England", groupe: "L", page: 99 },
    "ENG16": { nom: "Phil Foden", equipe: "England", groupe: "L", page: 99 },
    "ENG17": { nom: "Bukayo Saka", equipe: "England", groupe: "L", page: 99 },
    "ENG18": { nom: "Harry Kane", equipe: "England", groupe: "L", page: 99 },
    "ENG19": { nom: "Marcus Rashford", equipe: "England", groupe: "L", page: 99 },
    "ENG20": { nom: "Ollie Watkins", equipe: "England", groupe: "L", page: 99 },
    "CRO1": { nom: "Emblem", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO2": { nom: "Dominik Livaković", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO3": { nom: "Duje Caleta-Car", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO4": { nom: "Josko Gvardiol", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO5": { nom: "Josip Stanišić", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO6": { nom: "Luka Vušković", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO7": { nom: "Josip Sutalo", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO8": { nom: "Kristijan Jakic", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO9": { nom: "Luka Modrić", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO10": { nom: "Mateo Kovacic", equipe: "Croatia", groupe: "L", page: 100 },
    "CRO11": { nom: "Martin Baturina", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO12": { nom: "Lovro Majer", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO13": { nom: "Team Photo", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO14": { nom: "Mario Pasalic", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO15": { nom: "Petar Sucic", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO16": { nom: "Ivan Perišić", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO17": { nom: "Marco Pasalic", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO18": { nom: "Ante Budimir", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO19": { nom: "Andrej Kramarić", equipe: "Croatia", groupe: "L", page: 101 },
    "CRO20": { nom: "Franjo Ivanovic", equipe: "Croatia", groupe: "L", page: 101 },
    "GHA1": { nom: "Emblem", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA2": { nom: "Lawrence Ati Zigi", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA3": { nom: "Tariq Lamptey", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA4": { nom: "Mohammed Salisu", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA5": { nom: "Alidu Seidu", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA6": { nom: "Alexander Djiku", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA7": { nom: "Gideon Mensah", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA8": { nom: "Caleb Yirenkyi", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA9": { nom: "Abdul Issahaku Fatawu", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA10": { nom: "Thomas Partey", equipe: "Ghana", groupe: "L", page: 102 },
    "GHA11": { nom: "Salis Abdul Samed", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA12": { nom: "Kamaldeen Sulemana", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA13": { nom: "Team Photo", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA14": { nom: "Mohammed Kudus", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA15": { nom: "Inaki Williams", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA16": { nom: "Jordan Ayew", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA17": { nom: "Andrew Ayew", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA18": { nom: "Joseph Paintsil", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA19": { nom: "Osman Bukari", equipe: "Ghana", groupe: "L", page: 103 },
    "GHA20": { nom: "Antoine Semenyo", equipe: "Ghana", groupe: "L", page: 103 },
    "PAN1": { nom: "Emblem", equipe: "Panama", groupe: "L", page: 104 },
    "PAN2": { nom: "Orlando Mosquera", equipe: "Panama", groupe: "L", page: 104 },
    "PAN3": { nom: "Luis Mejia", equipe: "Panama", groupe: "L", page: 104 },
    "PAN4": { nom: "Fidel Escobar", equipe: "Panama", groupe: "L", page: 104 },
    "PAN5": { nom: "Andres Andrade", equipe: "Panama", groupe: "L", page: 104 },
    "PAN6": { nom: "Michael Amir Murillo", equipe: "Panama", groupe: "L", page: 104 },
    "PAN7": { nom: "Eric Davis", equipe: "Panama", groupe: "L", page: 104 },
    "PAN8": { nom: "Jose Cordoba", equipe: "Panama", groupe: "L", page: 104 },
    "PAN9": { nom: "Cesar Blackman", equipe: "Panama", groupe: "L", page: 104 },
    "PAN10": { nom: "Cristian Martinez", equipe: "Panama", groupe: "L", page: 104 },
    "PAN11": { nom: "Aníbal Godoy", equipe: "Panama", groupe: "L", page: 105 },
    "PAN12": { nom: "Adalberto Carrasquilla", equipe: "Panama", groupe: "L", page: 105 },
    "PAN13": { nom: "Team Photo", equipe: "Panama", groupe: "L", page: 105 },
    "PAN14": { nom: "Édgar Bárcenas", equipe: "Panama", groupe: "L", page: 105 },
    "PAN15": { nom: "Carlos Harvey", equipe: "Panama", groupe: "L", page: 105 },
    "PAN16": { nom: "Ismael Díaz", equipe: "Panama", groupe: "L", page: 105 },
    "PAN17": { nom: "Jose Fajardo", equipe: "Panama", groupe: "L", page: 105 },
    "PAN18": { nom: "Cecilio Waterman", equipe: "Panama", groupe: "L", page: 105 },
    "PAN19": { nom: "Jose Luiz Rodriguez", equipe: "Panama", groupe: "L", page: 105 },
    "PAN20": { nom: "Alberto Quintero", equipe: "Panama", groupe: "L", page: 105 },
    "FWC9": { nom: "Italy 1934 FIFA World Cup History", equipe: "History", groupe: null, page: 106 },
    "FWC10": { nom: "Uruguay 1950 FIFA World Cup History", equipe: "History", groupe: null, page: 106 },
    "FWC11": { nom: "West Germany 1954 FIFA World Cup History", equipe: "History", groupe: null, page: 107 },
    "FWC12": { nom: "Brazil 1962 FIFA World Cup History", equipe: "History", groupe: null, page: 107 },
    "FWC13": { nom: "West Germany 1974 FIFA World Cup History", equipe: "History", groupe: null, page: 107 },
    "FWC14": { nom: "Argentina 1986 FIFA World Cup History", equipe: "History", groupe: null, page: 108 },
    "FWC15": { nom: "Brazil 1994 FIFA World Cup History", equipe: "History", groupe: null, page: 108 },
    "FWC16": { nom: "Brazil 2002 FIFA World Cup History", equipe: "History", groupe: null, page: 109 },
    "FWC17": { nom: "Italy 2006 FIFA World Cup History", equipe: "History", groupe: null, page: 109 },
    "FWC18": { nom: "Germany 2014 FIFA World Cup History", equipe: "History", groupe: null, page: 109 },
    "FWC19": { nom: "Argentina 2022 FIFA World Cup History", equipe: "History", groupe: null, page: 109 },
};
